package vip.hyzt.questions;

import org.junit.Test;

public class Topic1704HalvesAreAlikeTests {

    @Test
    public void halvesAreAlike() {
        Topic1704HalvesAreAlike topic1704HalvesAreAlike = new Topic1704HalvesAreAlike();
        System.out.printf("res: %b\n", topic1704HalvesAreAlike.halvesAreAlike("book"));
        System.out.printf("res: %b\n", topic1704HalvesAreAlike.halvesAreAlike("qqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmm"));
        System.out.printf("res: %b\n", topic1704HalvesAreAlike.halvesAreAlike("qqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmmqqwweerrttyyuuiiooppaassddffgghhjjkkllzzxxccvvbbnnmmwwqqeerrttyyiiuuppoossaaddggffjjhhkkzzllvcvcnbnbmm"));
    }

}
